name: Docker Debian Image Vulnerability Scan
permissions:
  contents: read
  pull-requests: write

on:
  schedule:
    - cron: '30 1 */5 * *'
  workflow_dispatch: ~

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    # Step 2: Log in to Docker Hub with Docker Hub credentials
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    # Step 3: Pull the image from GitHub Packages
    - name: Pull Docker Image from GitHub Packages
      run: |
        docker pull ghcr.io/shuricksumy/docker-wgdashboard:debian-latest

    # Step 4: Run Docker Scout to scan the image
    - name: Analyze for critical and high CVEs
      uses: docker/scout-action@v1
      id: docker-scout-cves
      with:
        command: cves,recommendations
        image: ghcr.io/shuricksumy/docker-wgdashboard:debian-latest
        sarif-file: sarif.output.json
        summary: true

    - name: Upload Scan Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vulnerability-scan-report
        path: sarif.output.json
